// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Cz5c3wSTD1oqS_Jiu8dAFwlMJOGHy2w',
    appId: '1:330127101174:web:9c99da5832da2af2ae70d7',
    messagingSenderId: '330127101174',
    projectId: 'healwiz-da28a',
    authDomain: 'healwiz-da28a.firebaseapp.com',
    storageBucket: 'healwiz-da28a.appspot.com',
    measurementId: 'G-N2CE55G8MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC48Nsv3-NnwAhTcppRYV54mQJ2qulZKTk',
    appId: '1:373648071484:android:eb4e3ea050c7ee7f4d5c39',
    messagingSenderId: '373648071484',
    projectId: 'test-87fde',
    databaseURL: 'https://test-87fde-default-rtdb.firebaseio.com',
    storageBucket: 'test-87fde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWjCKyzetAv18mXdwG-K3jcJViO9UMTzM',
    appId: '1:330127101174:ios:e4c6f5c6b3e283dfae70d7',
    messagingSenderId: '330127101174',
    projectId: 'healwiz-da28a',
    storageBucket: 'healwiz-da28a.appspot.com',
    iosBundleId: 'com.example.healwiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWjCKyzetAv18mXdwG-K3jcJViO9UMTzM',
    appId: '1:330127101174:ios:ad610668f1d76596ae70d7',
    messagingSenderId: '330127101174',
    projectId: 'healwiz-da28a',
    storageBucket: 'healwiz-da28a.appspot.com',
    iosBundleId: 'com.example.healwiz.RunnerTests',
  );
}